export const funfacts = [
  "Tady se nic nestalo, ale věděli jste, že aceton je možné cítit z dechu diabetiků? Pokud jim chybí inzulin, zůstává cukr v krvi a z těla se začnou uvolňovat látky, které obsahují aceton. Dech pak zavání jako kdyby pili alkohol.",
  "Tady se nic nestalo, ale věděli jste, že oblíbená čistící kombinace ocet a jedlá soda nedělá vůbec nic? To, že to hezky pění, neznamená, že to čistí lépe. Víc si člověk pomůže samotným octem.",
  "Tady se nic nestalo, ale věděli jste, že Krtka si můžete v drogerii jako je Teta koupit daleko levněji? Stačí hledat hydroxid!",
  "Tady se nic nestalo, ale věděli jste, že kocovině se téměř nedá vyhnout? Naše tělo totiž rozkládá ethanol přes meziprodukt acetaldehyd, který je pro naše tělo toxický a způsobuje tak nevolnosti.",
  "Tady se nic nestalo, ale věděli jste, že hydroxid sodný se používá k výrobě mýdel? Skvěle totiž reaguje s tuky a tvoří tak glycerol, který tvoří mýdlo.",
  "Tady se nic nestalo, ale věděli jste, že pach bazénu necítíte proto, že by ho dezinfikovali chlorem? Savo, kterým se bazény čistí, totiž reaguje s močovinou z potu a jiných tělesných tekutin ve vodě. Vzniká tak chloramin, který smrdí jako chlor.",
  "Tady se nic nestalo, ale věděli jste, proč je vůně čerstvě posečené trávy příjemná lidem? Podle vědců je to z toho důvodu, že nám vůně připomíná jídlo. Látka, které se říká zelené listové fotily, se uvolňuje, když dozrává ovoce nebo se krájí zelenina.",
  "Tady se nic nestalo, ale věděli jste, že kuchyňská sůl nebo také chlorid sodný je esenciální pro lidský organismus? Je velmi důležitá pro přenos nervových vzruchů, stahování svalů a rovnováhu tělních tekutin.",
  "Tady se nic nestalo, ale věděli jste, že Savo má v sobě už samo o sobě NaOH? Používá se jako konzervant pro chlornan sodný.",
  "Tady se nic nestalo, ale věděli jste, že nerezová ocel může zreznout? Pokud necháte nerez v kontaktu se savem, začne korodovat",
  "Tady se nic nestalo, ale věděli jste, že když postříkáte kurkumu savem, zrudne?",
  "Tady se nic nestalo, ale věděli jste, že i vodou se můžete otrávit? Tělo se při nadměrném příjmu vody nezvládá vypořádat s rozdíly koncentrací minerálních látek. Buňky se začnou nafukovat a následkem toho odumírat.",
  "Tady se nic nestalo, ale věděli jste, že vůni deště se jinak říká petrichor? Vznikne při dopadu kapky deště na zem, kde se může vytvořit aerosol obsahující rostlinné oleje, bakterie a organické sloučeniny.",
  "Tady se nic nestalo, ale věděli jste, že jeden z nejstarších známých receptů je recept na pivo? Byl napsaný na hliněné destičce, pocházel ze Sumeru a datuje se do doby kolem roku 1800 př.n.l.",
  "Tady se nic nestalo, ale věděli jste, že klasický ocet můžete využít jako herbicid? Stačí ho nalít přímo na nežádoucí rostlinu.",
  "Tady se nic nestalo, ale věděli jste, že lepivých fleků po lepenkách a nálepkách se dá jednoduše zbavit? K odstranění můžete použít odlakovač s obsahem acetonu, jen si ověřte, jak s ním zacházet.",
  "Tady se nic nestalo, ale věděli jste, že aktivní látka v pepřovém spreji je kapsaicin? Látka, která se získává z chili papriček. Není pak divu, že dráždí oči, způsobuje bolest, dočasnou slepotu a slzení.",
  "Tady se nic nestalo, ale věděli jste, že peroxid vodíku se dá použít k bělení zubů? Je však potřeba dbát především na vlastní bezpečnost, můžete si poškodit sklovinu.",
  "Tady se nic nestalo, ale věděli jste, že sloučenina dihydrogen monoxid nebo také DHMO je sousloví, které se používá k parodování fobie z chemikálií? Nejedná se totiž o nic jiného než o H2O neboli vodu.",
  "Tady se nic nestalo, ale věděli jste, že sloučenina capsaicin je důvodem, proč jsou chilli papričky pálivé? Kapsaicin se totiž napojí na receptory bolesti v našich ústech, které vytvoří pocit pikantnosti.",
  "Tady se nic nestalo, ale věděli jste, že chemická sloučenina zvaná vanilin dodává vanilce charakteristickou chuť a vůni? Zajímavé je, že vanilin se nachází také v ligninovém odpadu, který je vedlejším produktem průmyslu dřevní hmoty - mimo jiné výroby papíru. Malé množství je získáváno i z tohoto zdroje.",
  "Tady se nic nestalo, ale věděli jste, že kyslina citronová se průmyslově nevyrábí z citrónu? K běžné průmyslové výrobě se využívá plísňová kultura Aspergillus niger a sacharóza.",
  "Tady se nic nestalo, ale věděli jste, že radium se v dvacátém století používálo v běžných produktech jako zubní pasta nebo krém na obličej? Produkty měly mít údajně díky radiu léčivé účinky.",
  "Tady se nic nestalo, ale věděli jste, že sycené nápoje jsou vytvořené přidáním CO2 za zvýšeného tlaku? Po otevření je tlak uvolní a tím se plyn začne v bublinách uvolňovat.",
  "Tady se nic nestalo, ale věděli jste, že zlato je ceněné nejen pro svou barvu a krásu? Důležitá je především nereaktivita s kyslíkem. Díky ní  nekoroduje a tím je uchována jeho hodnota.",
  "Tady se nic nestalo, ale věděli jste, že gallium vám může roztát v ruce? Má totiž bod tání na přibližně 29,8 stupňů Celsia a teplota těla způsobí jeho tání.",
  "Tady se nic nestalo, ale věděli jste, že jedlá soda vám může pomoct s kocovinou? Jedlá soda totiž pomáhá se zmírněním pálení žáhy a zažívacími problémy. Proto je také hlavní složkou vyprošťovacích tablet.",
  "Tady se nic nestalo, ale věděli jste, že solným roztokem se dá ulehčit bolestem v krku? Odstraňuje totiž přebytek tekutin ze zanícených hlenových membrán v krku, a snižuje tím otok.",
  "Tady se nic nestalo, ale věděli jste, že i železo se dá rozpustit? Kyselina sírová je natolik silná kyselina, že dokáže rozpouštět i takové látky jako je železo.",
  'Tady se nic nestalo, ale věděli jste, že reakce mezi kyselinou sírovou a cukrem může způsobit vznícení? Chemická reakce je exotermní a způsobuje efekt známý jako "černý prach".',
  "Tady se nic nestalo, ale věděli jste, že voda je jediná látka, která se při tuhnutí namísto smršťování rozšiřuje? Tento fenomén způsobuje, že led plave na hladině vody, což je důležité pro ekosystémy vodních prostředí, protože umožňuje udržovat teplotu vody relativně stabilní.",
  "Tady se nic nestalo, ale věděli jste, že CO2 v sycených nápojích tvoří pod tlakem v nápojích kyselinu uhličitou?",
];
