import savo from './img/savo.png';
import ocet from './img/ocet.png';
import peroxid from './img/peroxid.png';

export const chemicals = [
  {
    id: 'Krtek',
    nameOfProduct: 'Krtek',
    nameOfChemical: 'Hydroxid sodný',
    otherProducts: 'Domestos',
    use: 'Čištění odpadů, kotlů, potrubí, odmašťovací lázně, bělení a barvení textilií',
    specification: 'Bílý prášek, bez zápachu',
    warningSign: corrosive,
    url: savo,
  },
  {
    id: 'Ocet',
    nameOfProduct: 'Ocet',
    nameOfChemical: 'Kyselina octová',
    otherProducts: 'Univerzální a octové čističe',
    use: 'Odmašťuje, odstraňuje usazeniny a nečistoty, leští, uvolňuje ucpané odpady, změkčuje prádlo, dále působí proti plísním',
    specification: 'Ostrý octový zápach, bezbarvá kapalina',
    warningSign: 'corrosive, flammable',
    url: ocet,
  },
  {
    id: 'Aceton',
    nameOfProduct: 'Odlakovač (s acetonem)',
    nameOfChemical: 'Aceton',
    otherProducts: 'Ředidla',
    use: 'Odmašťování a čištění povrchů, odstraňování nátěrů barvy',
    specification: 'bezbarvá kapalina s výrazným zápachem',
    warningSign: 'flammable',
    url: savo,
  },
  {
    id: 'Amoniak',
    nameOfProduct: 'Okena',
    nameOfChemical: 'Sloučeniny s amoniakem',
    otherProducts: 'Hnojiva',
    use: 'Bělící a čistící účinky, hnojiva, chladivo',
    specification: 'Bezbarvý plyn se štiplavým zápachem',
    warningSign: 'corrosiv, dangerous, lebka',
    url: ocet,
  },
  {
    id: 'Peroxid',
    nameOfProduct: 'Peroxid vodíku',
    nameOfChemical: 'Peroxid vodíku',
    otherProducts: 'Dezinfekce na plochy',
    use: 'Bělící účinky, dezinfekční účinky',
    specification: 'Čirá namodralá kapalina',
    warningSign: 'corrosive, silný oxidant',
    url: peroxid,
  },
  {
    id: 'Savo',
    nameOfProduct: 'Savo',
    nameOfChemical: 'Chlornan sodný',
    otherProducts: 'Bělidlo, domestos',
    use: 'Čištění podlah a povrchů, dezinfekce',
    specification: 'Roztok, smrdí jako bazén',
    warningSign: 'corrosive, dangerous',
    url: savo,
  },
  {
    id: 'Ethanol',
    nameOfProduct: 'Líh',
    nameOfChemical: 'Ethanol',
    otherProducts: 'Dezinfekce, čistič povrchů',
    use: 'čištění, odmašťování, odstraňování některých druhů skvrn z textilu',
    specification: 'bezbarvá tekutina',
    warningSign: 'flammable',
    url: savo,
  },
  {
    id: 'Citron',
    nameOfProduct: 'Kyselina citronová',
    nameOfChemical: 'Kyselina citronová',
    otherProducts: 'Prostředky k čištění vodního kamene',
    use: 'Vaření, pečení, úklid',
    specification: 'Bezbarvé krystaly bez zápachu',
    warningSign: 'dráždivé',
    url: ocet,
  },
];
